### ISSUE TITLE
Remove the icon from the accessibility tree

### ISSUE THREAD

**Issue by FlorianBoe** [reatlat/eleventy-plugin-phosphoricons#2]
Hi there!
I had the same idea today that it would be nice to use Phosphor icons in an 11ty shortcode and found your great plugin.

I have a suggestion regarding the accessibility of the generated code. Currently the embedded SVG icon is part of the accessibility tree and behaves like an image without alt text. It would be reported as an image by a screen reader or other assistive technology, but would not have an accessible name.

If an image is decorative, you would leave the alt attribute empty. For decorative SVG icons, the best practice is to remove them from the accessibility tree with `aria-hidden="true"`.

For more information, see these two articles:
- [Contextually Marking up accessible images and SVGs](https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html#svgs-that-are-decorative)
- [Accessible Icon Buttons](https://www.sarasoueidan.com/blog/accessible-icon-buttons/#icon-sitting-next-to-text)

**Comment by reatlat** [comment]
@FlorianBoe good catch! Thank you!
I will get the solution ready soon.
